name: upc_flutter_202510_1acc0238_eb_u202220829
description: "Explora y guarda tus eventos favoritos."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  equatable: ^2.0.5
  http: ^1.1.2
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/event_cover.jpg